baseURL = "https://ec2spotworkshops.com/"
languageCode = "en-us"
title = "EC2 Spot Workshops"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = true
description = "EC2 Spot Workshops"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = false
disableShortcutsTitle = false
disableInlineCopyToClipBoard = true
disableLandingPageButton = true

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]

# All privacy options enabled. There should not be 
# any cookies or privacy  
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    # This is required to avoid cookies on youtube integration
    privacyEnhanced = true


[[menu.shortcuts]]
name = "<i class='fas fa-external-link-alt'></i> Amazon EC2 Spot Instances"
url = "https://aws.amazon.com/ec2/spot/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i> Authors"
url = "/authors.html"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-info-circle'></i> Resources"
url = "/resources.html"
weight = 40

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Feedback / Questions?"
url = "mailto:ec2-spot-workshops@amazon.com"
weight = 30


[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ja]
    languageName = "Japanese"
    weight = 2
